[build]
  command = "parcel build index.html --no-minify" # Adjust based on your entry file
  publish = "dist" # Default output directory for Parcel

[context.production.environment]
  NODE_ENV = "production"
